/**
 * POST /api/stage — server-side virtual staging.
 *
 * The phone sends the source photo; the backend verifies the Supabase JWT,
 * consumes one credit with the service role, calls Gemini with the server-side
 * key, refunds on failure, and returns the staged image.
 *
 * Request (multipart/form-data):
 *   image          file, JPEG / PNG / WebP (sniffed from bytes), ≤ MAX_IMAGE_BYTES
 *   room_type      one of ROOM_TYPES
 *   style          one of STYLES
 *   request_id     UUID generated by the client; stable per user intent, reused on retry
 *   declutter_only "true" | "false" (optional)
 *   folder_id, source, batch_index  optional strings copied into ledger meta
 *
 * Response 200:
 *   { request_id, image_base64, mime_type, size, watermark, plan,
 *     credits_remaining, credit_status, model, latency_ms }
 *
 * Errors: 400 invalid_request · 401 unauthorized · 402 no_credits ·
 *         409 in_progress · 413 image_too_large · 422 blocked · 429 rate_limited ·
 *         500 server_error · 502 generation_failed · 503 not_configured · 504 timeout
 *
 * Idempotency model (request_id is the client's key for one intent):
 *   - consume is keyed on request_id (ledger unique index).
 *   - a finished generation is stored at {user}/_generations/{request_id}.jpg;
 *     a replay of the same request_id returns that object without regenerating
 *     or charging (covers "client timed out after the server delivered").
 *   - if a previous attempt failed and was refunded, the retry consumes under a
 *     fresh attempt key `{request_id}:r<ts>` so the ledger stays consistent.
 *   - if the key is consumed but there is neither a stored result nor a refund,
 *     an attempt is still running → 409.
 *
 * Watermark policy is decided here from profiles.plan (free → watermark) and
 * the client applies it.
 */
import { Hono } from "hono";
import { z } from "zod";
import { env } from "../env";
import { getSupabaseAdmin, verifyAccessToken } from "../lib/supabase-admin";
import { consumeCredit, refundCredit, hasRefundRow } from "../lib/credits";
import {
  ROOM_TYPES,
  STYLES,
  buildStagingPrompt,
  generateStagedImage,
  GeminiError,
  type ImageSize,
} from "../lib/gemini";

const MAX_IMAGE_BYTES = 12 * 1024 * 1024;
/** Multipart overhead allowance on top of the image when checking Content-Length up front. */
const MAX_BODY_BYTES = MAX_IMAGE_BYTES + 256 * 1024;
const GENERATIONS_PREFIX = "_generations";

const fieldsSchema = z.object({
  room_type: z.enum(ROOM_TYPES),
  style: z.enum(STYLES),
  request_id: z.string().uuid(),
  declutter_only: z
    .union([z.literal("true"), z.literal("false")])
    .optional()
    .transform((v) => v === "true"),
  folder_id: z.string().max(128).optional(),
  source: z.string().max(32).optional(),
  batch_index: z.string().max(8).optional(),
});

// ─── Image type sniffing (never trust the multipart Content-Type) ─────────────
type SniffedMime = "image/jpeg" | "image/png" | "image/webp";

function sniffImageMime(buf: Buffer): SniffedMime | null {
  if (buf.length < 12) return null;
  if (buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return "image/jpeg";
  if (buf[0] === 0x89 && buf[1] === 0x50 && buf[2] === 0x4e && buf[3] === 0x47) return "image/png";
  if (buf.subarray(0, 4).toString("ascii") === "RIFF" && buf.subarray(8, 12).toString("ascii") === "WEBP") return "image/webp";
  return null;
}

// ─── Per-user rate limiting (in-memory; fine for a single Railway instance) ──
const RATE_WINDOW_MS = 60 * 60 * 1000;
const RATE_MAX_PER_WINDOW = Number(env.STAGE_RATE_LIMIT_PER_HOUR);
const RATE_MAX_INFLIGHT = Number(env.STAGE_MAX_INFLIGHT_PER_USER);

interface RateEntry { stamps: number[]; inflight: number }
const rate = new Map<string, RateEntry>();

function takeRateSlot(userId: string): "ok" | "hourly" | "inflight" {
  const now = Date.now();
  const entry = rate.get(userId) ?? { stamps: [], inflight: 0 };
  entry.stamps = entry.stamps.filter((t) => now - t < RATE_WINDOW_MS);
  if (entry.inflight >= RATE_MAX_INFLIGHT) {
    rate.set(userId, entry);
    return "inflight";
  }
  if (entry.stamps.length >= RATE_MAX_PER_WINDOW) {
    rate.set(userId, entry);
    return "hourly";
  }
  entry.stamps.push(now);
  entry.inflight += 1;
  rate.set(userId, entry);
  return "ok";
}

function releaseRateSlot(userId: string) {
  const entry = rate.get(userId);
  if (entry) entry.inflight = Math.max(0, entry.inflight - 1);
}

// Periodic sweep so the map does not grow forever.
setInterval(() => {
  const now = Date.now();
  for (const [k, v] of rate) {
    v.stamps = v.stamps.filter((t) => now - t < RATE_WINDOW_MS);
    if (v.stamps.length === 0 && v.inflight === 0) rate.delete(k);
  }
}, 10 * 60 * 1000).unref?.();

// ─── Plan policy (allowlist: anything unknown is treated as free) ────────────
const PAID_PLANS = new Set(["professional", "scale", "unlimited", "starter", "pro", "brokerage"]);

function policyForPlan(plan: string): { watermark: boolean; size: ImageSize; paid: boolean } {
  const paid = PAID_PLANS.has(plan);
  return {
    paid,
    watermark: !paid,
    size: paid ? (env.GEMINI_PAID_IMAGE_SIZE as ImageSize) : "1K",
  };
}

// ─── Stored generations (replay protection) ──────────────────────────────────
function storedPath(userId: string, requestId: string): string {
  return `${userId}/${GENERATIONS_PREFIX}/${requestId}.jpg`;
}

async function loadStoredGeneration(
  admin: NonNullable<ReturnType<typeof getSupabaseAdmin>>,
  userId: string,
  requestId: string,
): Promise<{ base64: string; mimeType: string } | null> {
  const { data, error } = await admin.storage.from(env.STAGE_OUTPUT_BUCKET).download(storedPath(userId, requestId));
  if (error || !data) return null;
  const buf = Buffer.from(await data.arrayBuffer());
  if (buf.length === 0) return null;
  return { base64: buf.toString("base64"), mimeType: data.type || sniffImageMime(buf) || "image/png" };
}

async function saveStoredGeneration(
  admin: NonNullable<ReturnType<typeof getSupabaseAdmin>>,
  userId: string,
  requestId: string,
  base64: string,
  mimeType: string,
): Promise<boolean> {
  const { error } = await admin.storage
    .from(env.STAGE_OUTPUT_BUCKET)
    .upload(storedPath(userId, requestId), Buffer.from(base64, "base64"), { contentType: mimeType, upsert: true });
  if (error) {
    console.error(`[Stage] could not store generation ${requestId} for ${userId}: ${error.message}`);
    return false;
  }
  return true;
}

// ─── Router ──────────────────────────────────────────────────────────────────
export const stageRouter = new Hono();

stageRouter.get("/", (c) => c.json({ ok: true }));

stageRouter.post("/", async (c) => {
  // ── 1. Auth ───────────────────────────────────────────────────────────────
  const authHeader = c.req.header("Authorization") ?? "";
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7).trim() : "";
  if (!token) return c.json({ error: "unauthorized", message: "Missing bearer token" }, 401);

  const admin = getSupabaseAdmin();
  if (!admin || !env.GEMINI_API_KEY) {
    console.error("[Stage] Not configured: supabase or GEMINI_API_KEY missing");
    return c.json({ error: "not_configured", message: "Staging service is not configured" }, 503);
  }

  const user = await verifyAccessToken(token);
  if (!user) return c.json({ error: "unauthorized", message: "Invalid or expired token" }, 401);

  // ── 2. Body size gate before buffering anything ───────────────────────────
  const declaredLength = Number(c.req.header("Content-Length") ?? "0");
  if (declaredLength > MAX_BODY_BYTES) {
    return c.json({ error: "image_too_large", message: `Image exceeds ${MAX_IMAGE_BYTES} bytes` }, 413);
  }

  // ── 3. Parse body ─────────────────────────────────────────────────────────
  let body: Record<string, string | File>;
  try {
    body = (await c.req.parseBody()) as Record<string, string | File>;
  } catch (err) {
    return c.json({ error: "invalid_request", message: `Could not parse form body: ${String(err)}` }, 400);
  }

  const image = body.image;
  if (!(image instanceof File)) {
    return c.json({ error: "invalid_request", message: "Missing image file field 'image'" }, 400);
  }
  if (image.size > MAX_IMAGE_BYTES) {
    return c.json({ error: "image_too_large", message: `Image exceeds ${MAX_IMAGE_BYTES} bytes` }, 413);
  }
  const buf = Buffer.from(await image.arrayBuffer());
  const mimeType = sniffImageMime(buf);
  if (!mimeType) {
    return c.json({ error: "invalid_request", message: "Image must be JPEG, PNG or WebP" }, 400);
  }

  const parsed = fieldsSchema.safeParse({
    room_type: body.room_type,
    style: body.style,
    request_id: body.request_id,
    declutter_only: body.declutter_only,
    folder_id: body.folder_id,
    source: body.source,
    batch_index: body.batch_index,
  });
  if (!parsed.success) {
    return c.json({ error: "invalid_request", message: "Invalid fields", issues: parsed.error.issues }, 400);
  }
  const fields = parsed.data;
  const requestId = fields.request_id;

  // ── 4. Rate limit ─────────────────────────────────────────────────────────
  const slot = takeRateSlot(user.id);
  if (slot !== "ok") {
    console.warn(`[Stage] rate limited user=${user.id} reason=${slot}`);
    return c.json(
      {
        error: "rate_limited",
        message: slot === "inflight" ? "Too many stagings in progress" : "Hourly staging limit reached",
      },
      429,
    );
  }

  const startedAt = Date.now();
  const deadlineAt = startedAt + Number(env.STAGE_TOTAL_DEADLINE_MS);
  let creditConsumedNow = false;
  let refunded = false;
  /** Ledger key for THIS attempt (request_id, or request_id:r<ts> after a refund). */
  let ledgerKey = requestId;
  let generationId: string | null = null;

  const ledgerMeta: Record<string, string> = {
    room_type: fields.room_type,
    style: fields.style,
    source: fields.source ?? "proxy",
    intent_request_id: requestId,
    ...(fields.folder_id ? { folder_id: fields.folder_id } : {}),
    ...(fields.batch_index ? { batch_index: fields.batch_index } : {}),
    ...(fields.declutter_only ? { declutter_only: "true" } : {}),
  };

  const refundIfNeeded = async (): Promise<number | null> => {
    if (!creditConsumedNow || refunded) return null;
    refunded = true;
    return refundCredit(admin, user.id, ledgerKey, ledgerMeta);
  };

  try {
    // ── 5. Plan / policy (a DB error here must not charge or downgrade) ────
    const { data: profile, error: profileErr } = await admin
      .from("profiles")
      .select("plan")
      .eq("user_id", user.id)
      .maybeSingle();
    if (profileErr) {
      console.error(`[Stage] profile read failed user=${user.id}: ${profileErr.message}`);
      return c.json({ error: "server_error", message: "Could not load your plan. Please try again." }, 500);
    }
    const plan = ((profile?.plan as string | null) ?? "free").toLowerCase();
    const policy = policyForPlan(plan);

    // ── 6. Consume credit (idempotent on request_id) ────────────────────────
    let consume = await consumeCredit(admin, user.id, requestId, ledgerMeta);

    if (consume.status === "already_processed") {
      // (a) Finished before and stored → replay without regenerating or charging.
      const stored = await loadStoredGeneration(admin, user.id, requestId);
      if (stored) {
        console.log(`[Stage] replay user=${user.id} req=${requestId}`);
        return c.json({
          request_id: requestId,
          image_base64: stored.base64,
          mime_type: stored.mimeType,
          size: policy.size,
          watermark: policy.watermark,
          plan,
          credits_remaining: consume.balance,
          credit_status: "replayed",
          model: env.GEMINI_MODEL,
          latency_ms: Date.now() - startedAt,
        });
      }
      // (b) Previous attempt failed and was refunded → charge a fresh attempt key.
      if (await hasRefundRow(admin, user.id, requestId)) {
        ledgerKey = `${requestId}:r${Date.now().toString(36)}`;
        consume = await consumeCredit(admin, user.id, ledgerKey, ledgerMeta);
      } else {
        // (c) Consumed, not stored, not refunded → still running (or crashed mid-way).
        console.warn(`[Stage] in_progress user=${user.id} req=${requestId}`);
        return c.json(
          { error: "in_progress", message: "This photo is still being staged. Please wait a moment.", credits_remaining: consume.balance },
          409,
        );
      }
    }

    if (consume.status === "no_credits") {
      return c.json(
        { error: "no_credits", message: "No credits remaining", credits_remaining: consume.balance ?? 0 },
        402,
      );
    }
    if (consume.status !== "ok") {
      console.error(`[Stage] credit consume error user=${user.id} key=${ledgerKey}: ${consume.message ?? consume.status}`);
      return c.json({ error: "server_error", message: "Could not reserve a credit" }, 500);
    }
    creditConsumedNow = true;

    // ── 7. Observability row (best effort; table may not exist yet) ─────────
    {
      const { data: gen } = await admin
        .from("generations")
        .upsert(
          {
            user_id: user.id,
            request_id: requestId,
            listing_id: null,
            room_type: fields.room_type,
            style: fields.style,
            options: { declutter_only: fields.declutter_only, size: policy.size, watermark: policy.watermark, source: fields.source ?? "proxy", ledger_key: ledgerKey },
            model: env.GEMINI_MODEL,
            input_bytes: buf.length,
            output_size: policy.size,
            status: "running",
            error: null,
          },
          { onConflict: "user_id,request_id" },
        )
        .select("id")
        .maybeSingle();
      generationId = (gen as { id?: string } | null)?.id ?? null;
    }

    // ── 8. Gemini ───────────────────────────────────────────────────────────
    const prompt = buildStagingPrompt(fields.room_type, fields.style, { declutterOnly: fields.declutter_only });

    let result;
    try {
      result = await generateStagedImage({
        imageBase64: buf.toString("base64"),
        mimeType,
        prompt,
        size: policy.size,
        deadlineAt,
      });
    } catch (err) {
      const gerr = err instanceof GeminiError ? err : new GeminiError("upstream_error", String(err));
      console.error(`[Stage] generation failed user=${user.id} req=${requestId} code=${gerr.code} status=${gerr.status ?? "-"} msg=${gerr.message}`);

      const balance = await refundIfNeeded();

      if (generationId) {
        await admin
          .from("generations")
          .update({ status: "refunded", error: `${gerr.code}`.slice(0, 200), latency_ms: Date.now() - startedAt })
          .eq("id", generationId);
      }

      const status =
        gerr.code === "blocked" ? 422 :
        gerr.code === "rate_limited" ? 429 :
        gerr.code === "not_configured" ? 503 :
        gerr.code === "timeout" ? 504 : 502;

      return c.json(
        {
          error: gerr.code === "blocked" ? "blocked" : gerr.code === "rate_limited" ? "upstream_rate_limited" : gerr.code === "timeout" ? "timeout" : "generation_failed",
          message: gerr.code === "blocked"
            ? "This photo could not be staged (content filter). Try a different photo."
            : "Staging failed. Your credit has been returned.",
          credits_remaining: balance,
        },
        status,
      );
    }

    // ── 9. Store for replay, then respond ───────────────────────────────────
    await saveStoredGeneration(admin, user.id, requestId, result.imageBase64, result.mimeType);

    const latencyMs = Date.now() - startedAt;
    if (generationId) {
      await admin
        .from("generations")
        .update({ status: "succeeded", latency_ms: latencyMs, output_size: result.sizeRequested })
        .eq("id", generationId);
    }
    console.log(`[Stage] ok user=${user.id} req=${requestId} plan=${plan} size=${result.sizeRequested} watermark=${policy.watermark} gemini_ms=${result.latencyMs} total_ms=${latencyMs}`);

    return c.json({
      request_id: requestId,
      image_base64: result.imageBase64,
      mime_type: result.mimeType,
      size: result.sizeRequested,
      watermark: policy.watermark,
      plan,
      credits_remaining: consume.balance,
      credit_status: "ok",
      model: result.model,
      latency_ms: latencyMs,
    });
  } catch (err) {
    console.error(`[Stage] unexpected error user=${user.id} req=${requestId}:`, err);
    const balance = await refundIfNeeded().catch(() => null);
    if (generationId) {
      await admin
        .from("generations")
        .update({ status: refunded ? "refunded" : "failed", error: String(err).slice(0, 200), latency_ms: Date.now() - startedAt })
        .eq("id", generationId)
        .then(() => undefined, () => undefined);
    }
    return c.json({ error: "server_error", message: "Unexpected error. Your credit has been returned.", credits_remaining: balance }, 500);
  } finally {
    releaseRateSlot(user.id);
  }
});
